name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 安装go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: 对go的代码进行打包
      run: go build -v ./...

    - name: 对go的代码进行测试
      run: go test -v ./...
